import datetime
from typing import Callable

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import pandas_datareader.data as web
import yfinance as yf
import yahoo_fin.stock_info as si

import xlsxwriter


nasdaqTickersAdj = []
nasdaqTickerErrors = []
nasdaq = si.tickers_nasdaq()
cnt = 4000
limit = 5000
amntTickers = len(nasdaq)

while cnt < limit:
    print(nasdaq[cnt], "start prozessing ticker", cnt, " of ", amntTickers)
    try:
        netIncome = si.get_cash_flow(nasdaq[cnt], yearly = True)
        netIncomeLastYear = netIncome.iloc[6] if netIncome.empty == False else [0]
        if netIncomeLastYear[0] > 1000000.0:
            nasdaqTickersAdj.append(nasdaq[cnt])
    except:
        nasdaqTickerErrors.append(nasdaq[cnt])
        print(nasdaq[cnt], "error occured")
    
    cnt = cnt + 1



#for ticker in nasdaq:
#    print(ticker, "start prozessing ticker", cnt, " of ", amntTickers)
    # try:
    #     netIncome = si.get_cash_flow(ticker, yearly = True)
    #     netIncomeLastYear = netIncome.iloc[6] if netIncome.empty == False else [0]
    #     if netIncomeLastYear[0] > 1000000.0:
    #         nasdaqTickersAdj.append(ticker)
    # except:
    #     nasdaqTickerErrors.append(ticker)
    #     print(ticker, "error occured")
    
    # cnt = cnt + 1

print(nasdaqTickersAdj)
print(nasdaqTickerErrors)

nasdaqTickersAdj1 = ['AADI', 'AAL', 'AAME', 'AAON', 'AAPL', 'AATC', 'AAWW', 'ABCB', 'ABCL', 'ABCM', 'ABIO', 'ABMD', 'ABNB', 'ABSI', 'ABVC', 'ACGL', 'ACGLN', 'ACGLO', 'ACHC', 'ACHL', 'ACHV', 'ACIU', 'ACIW', 'ACLS', 'ACMR', 'ACNT', 'ACQR', 'ACRS', 'ACRX', 'ACVA', 'ADAL', 'ADAP', 'ADBE', 'ADEA', 'ADER', 'ADES', 'ADI', 'ADIL', 'ADP', 'ADSK', 'ADTH', 'ADUS', 'ADVM', 'ADXN', 'AEAC', 'AEAE', 'AEHA', 'AEHR', 'AEI', 'AEIS', 'AEMD', 'AEP', 'AERC', 'AESE', 'AFAC', 'AFBI', 'AFCG', 'AFRM', 'AFYA', 'AGEN', 'AGFY', 'AGGR', 'AGIO', 'AGLE', 'AGMH', 'AGNC', 'AGNCM', 'AGNCN', 'AGNCO', 'AGNCP', 'AGTC', 'AHCO', 'AHI', 'AHRN', 'AIMC', 'AIRS', 'AIRT', 'AIRTP', 'AKAM', 'AKIC', 'AKTS', 'ALDX', 'ALGM', 'ALGN', 'ALGS', 'ALGT', 'ALKS', 'ALNY', 'ALOR', 'ALOT', 'ALPN', 'ALPP', 'ALRM', 'ALRS', 'ALTO', 'AMAL', 'AMAT', 'AMCX', 'AMD', 'AMED', 'AMEH', 'AMGN', 'AMKR', 'AMPG', 'AMPH', 'AMPL', 'AMRK', 'AMRN', 'AMSF', 'AMST', 'AMSWA', 'AMTB', 'AMTI', 'AMZN', 'ANDE', 'ANEB', 'ANGO', 'ANIK', 'ANSS', 'ANY', 'AOGO', 'AOSL', 'APA', 'APEI', 'APLT', 'APM', 'APOG', 'APP', 'APPF', 'APPS', 'APXI', 'AQB', 'AQMS', 'ARAY', 'ARBE', 'ARBK', 'ARCB', 'ARCC', 'ARDX', 'AREC', 'ARGU', 'ARGX', 'ARHS', 'ARKO', 'ARKOW', 'ARKR', 'ARLP', 'AROW', 'ARQT', 'ARRW', 'ARRY', 'ARTL', 'ARTNA', 'ARVL', 'ASLE', 'ASML', 'ASND', 'ASO', 'ASPS', 'ASTL', 'ASYS', 'ATAI', 'ATAX', 'ATEC', 'ATLC', 'ATLCP', 'ATLO', 'ATNF', 'ATNX', 'ATOS', 'ATRC', 'ATRI', 'ATSG', 'ATVI', 'ATY', 'AUB', 'AUBAP', 'AUBN', 'AUDC', 'AUR', 'AURA', 'AUTL', 'AVAC', 'AVAV', 'AVCO', 'AVGO', 'AVID', 'AVNW', 'AVPT', 'AXDX', 'AXGN', 'AXLA', 'AXTI', 'AZN', 'AZTA', 'BAFN', 'BANF', 'BANR', 'BAOS', 'BASE', 'BBCP', 'BBGI', 'BBIG', 'BBIO', 'BBLG', 'BBSI', 'BCAB', 'BCEL', 'BCML', 'BCOR', 'BCOV', 'BCOW', 'BCPC', 'BCRX', 'BCTX', 'BEAM', 'BEAT', 'BECN', 'BFIN', 'BFRI', 'BFST', 'BGCP', 'BGFV', 'BGNE', 'BGRY', 'BHAC', 'BIDU', 'BIGC', 'BIIB', 'BILI', 'BIMI', 'BIOL', 'BIOS', 'BITF', 'BIVI', 'BKNG', 'BKSC', 'BL', 'BLBX', 'BLDE', 'BLDP', 'BLFY', 'BLKB', 'BLMN', 'BLNG', 'BLRX', 'BLU', 'BMBL', 'BMEA', 'BMRN', 'BNGO', 'BNIX', 'BNOX', 'BNSO', 'BNTX', 'BOCN', 'BOKF', 'BON', 'BOOM', 'BOTJ', 'BPOP', 'BPRN', 'BPTH', 'BPTS', 'BPYPN', 'BPYPO', 'BPYPP', 'BRIV', 'BRKH', 'BRKL', 'BRKR', 'BRLT', 'BROG', 'BRP', 'BSBK', 'BSET', 'BSKY', 'BSQR', 'BSVN', 'BSY', 'BTAI', 'BTBT', 'BTMD', 'BTRS', 'BUSE', 'BVS', 'BWAY', 'BWC', 'BWEN', 'BWMX', 'BYFC', 'BYND', 'BYRN', 'BYTS', 'BZFD', 'CAAS', 'CAC', 'CACC', 'CADL', 'CAKE', 'CALM', 'CAN', 'CAPR', 'CARE', 'CARV', 'CASA', 'CASH', 'CASY', 'CATC', 'CATY', 'CBAN', 'CBAT', 'CBAY', 'CBRG', 'CBSH', 'CCAP', 'CCB', 'CCBG', 'CCEP', 'CCLP', 'CCNC', 'CCNE', 'CCNEP', 'CCOI', 'CCSI', 'CD', 'CDMO', 'CDNA', 'CDNS', 'CDRO', 'CDW', 'CDZI', 'CDZIP', 'CELH', 'CELZ', 'CENN', 'CENT']
nasdaqTickersAdj2 = ['CENTA', 'CERS', 'CFFI', 'CFLT', 'CFSB', 'CG', 'CGC', 'CGNX', 'CGO', 'CHCI', 'CHDN', 'CHI', 'CHK', 'CHKP', 'CHNR', 'CHRD', 'CHRS', 'CHRW', 'CHSCL', 'CHSCM', 'CHSCN', 'CHSCO', 'CHSCP', 'CHTR', 'CHUY', 'CHX', 'CHY', 'CIDM', 'CIFR', 'CINF', 'CIVB', 'CIZN', 'CLAR', 'CLBK', 'CLBT', 'CLFD', 'CLLS', 'CLMT', 'CLNE', 'CLOV', 'CLPS', 'CLPT', 'CLRM', 'CLRO', 'CLSK', 'CLST', 'CLWT', 'CLXT', 'CMBM', 'CMCA', 'CMCO', 'CMCSA', 'CME', 'CMPO', 'CMPS', 'CNEY', 'CNSL', 'CNTB', 'CNTX', 'CNTY', 'CNXC', 'COCO', 'CODA', 'CODX', 'COHU', 'COIN', 'COKE', 'COLB', 'COLI', 'COLL', 'COLM', 'CONN', 'COOP', 'CORT', 'CORZ', 'COST', 'COUP', 'COVA', 'COWN', 'CPAA', 'CPAR', 'CPRT', 'CPRX', 'CPSH', 'CPSS', 'CRAI', 'CRBP', 'CRBU', 'CRCT', 'CREC', 'CREG', 'CRESY', 'CRNC', 'CROX', 'CRSP', 'CRSR', 'CRTO', 'CRUS', 'CRZN', 'CSBR', 'CSCO', 'CSGP', 'CSGS', 'CSII', 'CSIQ', 'CSQ', 'CSSE', 'CSSEP', 'CSTE', 'CSWC', 'CSWI', 'CSX', 'CTAS', 'CTG', 'CTHR', 'CTIC', 'CTKB', 'CTRM', 'CTSH', 'CUEN', 'CULL', 'CUTR', 'CVBF', 'CVCO', 'CVLG', 'CVLY', 'CVT', 'CVV', 'CWBC', 'CWBR', 'CWST', 'CYAD', 'CYBE', 'CYCC', 'CYCCP', 'CYRX', 'CYT', 'CYTO', 'CYXT', 'CZFS', 'CZR', 'DADA', 'DALS', 'DAOO', 'DARE', 'DAVE', 'DAWN', 'DBTX', 'DBX', 'DCGO', 'DCOM', 'DCOMP', 'DDI', 'DFFN', 'DGICA', 'DGICB', 'DGII', 'DGLY', 'DGNU', 'DHC', 'DHCA', 'DHHC', 'DHIL', 'DIBS', 'DICE', 'DIOD', 'DISH', 'DJCO', 'DKDCA', 'DKNG', 'DLCA', 'DLHC', 'DLO', 'DLTH', 'DLTR', 'DMAC', 'DMLP', 'DMTK', 'DNUT', 'DOCU', 'DOGZ', 'DOOO', 'DORM', 'DOX', 'DPRO', 'DRCT', 'DRIO', 'DRMA', 'DRRX', 'DRTT', 'DRVN', 'DSGX', 'DSKE', 'DSP', 'DSWL', 'DUOL', 'DVAX', 'DXCM', 'DXLG', 'DYNT', 'EA', 'EAC', 'EBAC', 'EBAY', 'EBC', 'EBET', 'EBIX', 'EBMT', 'EBON', 'ECBK', 'EDAP', 'EDRY', 'EDUC', 'EEFT', 'EEIQ', 'EFSC', 'EFSCP', 'EFTR', 'EGAN', 'EGLE', 'EGLX', 'EHTH', 'EJH', 'EKSO', 'ELBM', 'ELTK', 'EM', 'EMBC', 'EMCF', 'EMKR', 'EML', 'ENPH', 'ENSC', 'ENSG', 'ENTG', 'ENTX', 'ENTXW', 'ENVB', 'ENVX', 'EOLS', 'EOSE', 'EPHY', 'EPIX', 'EQBK', 'EQIX', 'ERIC', 'ERIE', 'ERII', 'ERYP', 'ESAC', 'ESCA', 'ESEA', 'ESGR', 'ESGRO', 'ESGRP', 'ESSA', 'ETNB', 'ETSY', 'EVGN', 'EVO', 'EVOJ', 'EVOP', 'EVTV', 'EWBC', 'EWCZ', 'EXAI', 'EXAS', 'EXC', 'EXEL', 'EXPD', 'EXPE', 'EXPI', 'EXPO', 'EYE', 'EYPT', 'EZFL', 'EZGO', 'FA', 'FAMI', 'FANG', 'FANH', 'FAST', 'FBMS', 'FBNC', 'FCFS', 'FCNCA', 'FCNCO', 'FCNCP', 'FDUS', 'FEIM', 'FELE', 'FFBW', 'FFHL', 'FFIC', 'FFIN', 'FFIV', 'FFWM', 'FGBI', 'FGBIP', 'FGEN', 'FHLT', 'FHTX', 'FIAC', 'FICV', 'FINM', 'FINW', 'FISI', 'FISV', 'FITB', 'FITBI', 'FITBO', 'FITBP', 'FIVE', 'FIVN', 'FIZZ', 'FKWL', 'FLEX', 'FLGC', 'FLGT', 'FLL', 'FLWS', 'FMAO', 'FMBH', 'FMIV', 'FMNB', 'FNHC', 'FNKO', 'FNVT', 'FNWB', 'FNWD', 'FOCS', 'FOLD', 'FONR', 'FORA', 'FORM', 'FORR', 'FORTY', 'FOX', 'FOXA', 'FPAY', 'FRAF', 'FRBN', 'FRG', 'FRGAP', 'FRHC', 'FRME', 'FRMEP', 'FRON', 'FRPT', 'FRST', 'FRW', 'FSBC']
nasdaqTickersAdj3 = ['FSBW', 'FSEA', 'FSLR', 'FSRX', 'FSTR', 'FSV', 'FTAI', 'FTAIN', 'FTAIO', 'FTAIP', 'FTCI', 'FTEK', 'FTFT', 'FTNT', 'FTVI', 'FULC', 'FULT', 'FULTP', 'FUSB', 'FUTU', 'FVCB', 'FWRD', 'FXNC', 'FYBR', 'GABC', 'GAIA', 'GAIN', 'GALT', 'GAMB', 'GAMC', 'GBNY', 'GDEN', 'GDEV', 'GDS', 'GDST', 'GDYN', 'GEEX', 'GEG', 'GERN', 'GEVO', 'GFGD', 'GFS', 'GGAL', 'GGMC', 'GH', 'GHRS', 'GIII', 'GILD', 'GIPR', 'GIW', 'GLBS', 'GLHA', 'GLLI', 'GLNG', 'GLPG', 'GLPI', 'GLUE', 'GMAB', 'GNAC', 'GNFT', 'GNPX', 'GNTX', 'GNTY', 'GNUS', 'GOEVW', 'GOGL', 'GOOD', 'GOODN', 'GOODO', 'GOOG', 'GOOGL', 'GPAC', 'GPP', 'GPRE', 'GPRO', 'GRAB', 'GRCL', 'GRFS', 'GRIN', 'GROW', 'GRPH', 'GRPN', 'GRTS', 'GRTX', 'GRVY', 'GRWG', 'GSBC', 'GSHD', 'GSMG', 'GT', 'GTAC', 'GTBP', 'GTEC', 'GTH', 'GTHX', 'GTIM', 'GURE', 'GWAV', 'GWII', 'GWRS', 'GXII', 'HA', 'HAFC', 'HAIA', 'HAIN', 'HALL', 'HALO', 'HAS', 'HBAN', 'HBANM', 'HBANP', 'HBNC', 'HBT', 'HCCI', 'HCIC', 'HCII', 'HCM', 'HCP', 'HCSG', 'HCVI', 'HDSN', 'HEES', 'HELE', 'HEPS', 'HERA', 'HEXO', 'HFWA', 'HGEN', 'HHR', 'HIBB', 'HIII', 'HIMX', 'HITI', 'HIVE', 'HLAH', 'HLIT', 'HLNE', 'HLTH', 'HMNF', 'HMPT', 'HNNA', 'HNST', 'HOFT', 'HOLI', 'HOLX', 'HON', 'HOOD', 'HOPE', 'HOUR', 'HOWL', 'HPK', 'HPLT', 'HQI', 'HQY', 'HRMY', 'HRTX', 'HSDT', 'HSIC', 'HST', 'HSTM', 'HTBK', 'HTGM', 'HTLF', 'HTLFP', 'HTZ', 'HUBG', 'HUDI', 'HUMA', 'HURC', 'HURN', 'HWBK', 'HWC', 'HWKN', 'HYFM', 'HYW', 'HZNP', 'IAC', 'IART', 'IBEX', 'IBKR', 'IBOC', 'IBRX', 'IBTX', 'ICCC', 'ICCH', 'ICFI', 'ICHR', 'ICLR', 'ICMB', 'ICUI', 'ICVX', 'IDCC', 'IDEX', 'IDRA', 'IDXX', 'IEP', 'IFBD', 'IFRX', 'IGIC', 'IIIV', 'IIVIP', 'IKNA', 'IKT', 'ILMN', 'ILPT', 'IMCC', 'IMKTA', 'IMMR', 'IMOS', 'IMVT', 'IMXI', 'INBK', 'INCR', 'INCY', 'INDB', 'INDP', 'INDT', 'INM', 'INMD', 'INSM', 'INTC', 'INTG', 'INTU', 'INVA', 'INVE', 'INVO', 'INVZ', 'IOAC', 'IOBT', 'IONM', 'IONR', 'IONS', 'IOSP', 'IOVA', 'IPAR', 'IPDN', 'IPGP', 'IPWR', 'IQ', 'IRBT', 'IRDM', 'IREN', 'IRIX', 'IRMD', 'IROQ', 'IRTC', 'IRWD', 'ISPO', 'ISRG', 'ISUN', 'ITIC', 'ITOS', 'ITQ', 'ITRM', 'ITRN', 'IVAC', 'IVCB', 'IXHL', 'JACK', 'JAQC', 'JAZZ', 'JCIC', 'JD', 'JFIN', 'JG', 'JJSF', 'JKHY', 'JMAC', 'JOAN', 'JOFF', 'JRSH', 'JSPR', 'JUGG', 'JVA', 'JWAC', 'JWEL', 'JYNT', 'KAII', 'KAIR', 'KALA', 'KARO', 'KBAL', 'KDP', 'KE', 'KELYA', 'KELYB', 'KEQU', 'KFFB', 'KFRC', 'KHC', 'KIII', 'KINS', 'KLAQ', 'KLIC', 'KMPH', 'KNDI', 'KOSS', 'KPLT', 'KRNL', 'KRON', 'KRT', 'KTCC', 'KTRA', 'KTTA', 'KURA', 'KVHI', 'KXIN', 'KYMR', 'KZR', 'LAMR', 'LAND', 'LANDM', 'LANDO']
nasdaqTickersAdj4 = ['LAUR', 'LAZR', 'LAZY', 'LBC', 'LCA', 'LCID', 'LDHA', 'LECO', 'LEGA', 'LEGH', 'LEGN', 'LESL', 'LFUS', 'LGHL', 'LGIH', 'LGMK', 'LGND', 'LGNDV', 'LGO', 'LGTO', 'LGVC', 'LGVN', 'LHCG', 'LHDX', 'LI', 'LILM', 'LINC', 'LION', 'LIQT', 'LITE', 'LIVE', 'LIVN', 'LKCO', 'LMAT', 'LMB', 'LMFA', 'LMNL', 'LMST', 'LNT', 'LNW', 'LOAN', 'LOB', 'LOCO', 'LOPE', 'LOTZ', 'LOVE', 'LPCN', 'LPLA', 'LPRO', 'LQDT', 'LRCX', 'LRFC', 'LSBK', 'LSCC', 'LSEA', 'LSPR', 'LSXMA', 'LSXMB', 'LSXMK', 'LTBR', 'LTCH', 'LTRPA', 'LTRPB', 'LULU', 'LUNA', 'LVAC', 'LVLU', 'LVTX', 'LWAY', 'LX', 'LXRX', 'LYFT', 'LYL', 'LYLT', 'LYTS', 'MACA', 'MAPS', 'MAR', 'MARA', 'MARK', 'MASI', 'MASS', 'MATW', 'MAXN', 'MBIN', 'MBINM', 'MBINN', 'MBINO', 'MBINP', 'MBIO', 'MBNKP', 'MBRX', 'MBUU', 'MCBC', 'MCBS', 'MCFT', 'MCHP', 'MCRB', 'MCRI', 'MDB', 'MDLZ', 'MDRX', 'MDXH', 'ME', 'MEAC', 'MEDP', 'MELI', 'MEOA', 'MEOH', 'META', 'METC', 'METX', 'MFIN', 'MGEE', 'MGI', 'MGPI', 'MGTX', 'MGYR', 'MIGI', 'MIRO', 'MITK', 'MKSI', 'MKTX', 'MLAB', 'MLKN', 'MMAT', 'MMSI', 'MNDY', 'MNKD', 'MNMD', 'MNOV', 'MNRO', 'MNSB', 'MNSBP', 'MNST', 'MNTK', 'MNTS', 'MNTV', 'MNTX', 'MOFG', 'MOGO', 'MOLN', 'MON', 'MPB', 'MPWR', 'MRAM', 'MRBK', 'MRCY', 'MREO', 'MRKR', 'MRNA', 'MRNS', 'MRVI', 'MSAC', 'MSBI', 'MSEX', 'MSFT', 'MTBC', 'MTBCO', 'MTBCP', 'MTC', 'MTCH', 'MTCR', 'MTEM', 'MTEX', 'MTLS', 'MTP', 'MTSI', 'MTTR', 'MU', 'MVBF', 'MVIS', 'MVST', 'MXCT', 'MXL', 'MYFW', 'MYGN', 'MYMD', 'MYRG', 'MYSZ', 'NA', 'NAAC', 'NAAS', 'NAII', 'NARI', 'NATI', 'NAVI', 'NBIX', 'NBRV', 'NBSE', 'NCNO', 'NCPL', 'NCSM', 'NDAC', 'NDAQ', 'NDLS', 'NDRA', 'NDSN', 'NECB', 'NEGG', 'NEO', 'NEOG', 'NESR', 'NEWT', 'NEWTL', 'NEXI', 'NFBK', 'NFLX', 'NHIC', 'NICE', 'NICK', 'NISN', 'NIU', 'NKLA', 'NLOK', 'NMIH', 'NMRK', 'NMTC', 'NNDM', 'NOTV', 'NOVN', 'NPAB', 'NPCE', 'NRAC', 'NRBO', 'NRC', 'NRIM', 'NRSN', 'NSSC', 'NSTG', 'NSYS', 'NTAP', 'NTCT', 'NTES', 'NTGR', 'NTIC', 'NTNX', 'NTRS', 'NTRSO', 'NTWK', 'NURO', 'NUTX', 'NUVA', 'NUVL', 'NVCR', 'NVCT', 'NVDA', 'NVEE', 'NVEI', 'NVMI', 'NVNO', 'NWBI', 'NWE', 'NWLI', 'NWS', 'NWSA', 'NXPI', 'NXST', 'NXTP', 'NYMT', 'NYMTL', 'NYMTM', 'NYMTN', 'NYMTZ', 'NYXH', 'OB', 'OBLG', 'OBT', 'OCAX', 'OCFC', 'OCFCP', 'ODFL', 'OEPW', 'OFIX', 'OGI', 'OHPA', 'OIG', 'OIIM', 'OKTA', 'OKYO', 'OLED', 'OLK', 'OLLI', 'OLPX', 'OMAB', 'OMER', 'OMGA', 'OMIC', 'ON', 'ONDS', 'ONEM', 'ONEW', 'ONFO', 'OPAL', 'OPCH', 'OPEN', 'OPHC', 'OPINL', 'OPK', 'OPNT', 'OPRT', 'OPRX', 'OPT', 'ORGO', 'ORGS', 'ORLY', 'ORTX', 'OSBC', 'OSIS', 'OSS', 'OSTK', 'OSTR', 'OTEC', 'OTEX', 'OTIC', 'OTLK', 'OVBC', 'OVID', 'OVLY', 'OXUS', 'OZK', 'OZKAP', 'PAA', 'PACB', 'PACW', 'PACWP', 'PACX', 'PAGP', 'PAHC', 'PANL', 'PANW', 'PARA', 'PARAA', 'PARAP', 'PATK', 'PAX', 'PAYS', 'PAYX', 'PBAX', 'PBBK', 'PBFS', 'PBLA', 'PCAR', 'PCB', 'PCH', 'PCRX', 'PCSB', 'PCT', 'PCTTU', 'PCTY', 'PCX', 'PCYG', 'PDCE', 'PDCO', 'PDD', 'PDLB', 'PEBK', 'PECO', 'PENN', 'PEP', 'PERI', 'PETS', 'PETZ', 'PFBC', 'PFC', 'PFDR', 'PFG', 'PFHD', 'PFIS', 'PFSW', 'PFTA']
pommesBuden1 = ['AADR', 'AAPB', 'AAPD', 'AAPU', 'AAXJ', 'ACAB', 'ACAXR', 'ACWI', 'ACWX', 'ADRE', 'AGNG', 'AGZD', 'AIA', 'AIQ', 'AIRR', 'ALTY', 'AMID', 'AMZD', 'AMZU', 'ANGL', 'AOTG', 'APRE', 'AQWA', 'ARVR', 'ASCA', 'ASCB', 'ASET', 'ATRA', 'AVEO', 'AVGR', 'BANX', 'BBH', 'BFIT', 'BGRN', 'BHFAL', 'BIB', 'BICK', 'BIS', 'BITS', 'BJK', 'BKCH', 'BLCN', 'BLLD', 'BND', 'BNDW', 'BNDX', 'BNR', 'BOTZ', 'BPMC', 'BRNY', 'BSBE', 'BSCE', 'BSCM', 'BSCN', 'BSCO', 'BSCP', 'BSCQ', 'BSCR', 'BSCS', 'BSCT', 'BSCU', 'BSCV', 'BSCW', 'BSDE', 'BSJM', 'BSJN', 'BSJO', 'BSJP', 'BSJQ', 'BSJR', 'BSJS', 'BSJT', 'BSJU', 'BSMM', 'BSMN', 'BSMO', 'BSMP', 'BSMQ', 'BSMR', 'BSMS', 'BSMT', 'BSMU', 'BSMV', 'BTEC', 'BTF', 'BUG', 'BULD', 'BYOB', 'CACG', 'CARZ', 'CATH', 'CCSO', 'CDC', 'CDL', 'CECE', 'CEFA']
pommesBuden2 = ['CEY', 'CFA', 'CFO', 'CHB', 'CHEA', 'CHNA', 'CIBR', 'CID', 'CIL', 'CIRC', 'CIZ', 'CLOU', 'CLRC', 'CLRG', 'CNCR', 'CNFRL', 'COMT', 'CONL', 'COSM', 'CPAQ', 'CRDO', 'CSA', 'CSB', 'CSF', 'CSLM', 'CSML', 'CTEC', 'CUBA', 'CXSE', 'DALI', 'DALN', 'DAM', 'DAPP', 'DAX', 'DDIV', 'DEMZ', 'DGRE', 'DGRS', 'DGRW', 'DIVD', 'DMAT', 'DMXF', 'DRIV', 'DSPC', 'DUET', 'DVLU', 'DVOL', 'DVY', 'DWAS', 'DWAW', 'DWEQ', 'DWMC', 'DWSH', 'DWUS', 'DXGE', 'DXJS', 'EBIZ', 'ECOW', 'EDOC', 'EDUT', 'EEMA', 'EFAS', 'EKG', 'EMB', 'EMCB', 'EMIF', 'EMXC', 'EMXF', 'ENZL', 'EQRR', 'ESGD', 'ESGE', 'ESGU', 'ESMV', 'ESPO', 'ESTA', 'EUFN', 'EVGBC', 'EVGR', 'EVLMC', 'EVMT', 'EVSTC', 'EWEB', 'EWJV', 'EWZS', 'FAAR', 'FAB', 'FAD', 'FALN', 'FBZ', 'FCA', 'FCAL', 'FCEF', 'FCVT', 'FDIG', 'FDNI', 'FDT', 'FDTS', 'FEM', 'FEMA', 'FEMB', 'FEMS', 'FEP', 'FEUZ', 'FEX', 'FGM', 'FGMC', 'FICS', 'FID', 'FINX', 'FIVR', 'FIXD', 'FJP', 'FKU', 'FLN', 'FMB', 'FMET', 'FMHI', 'FNK', 'FNX', 'FNY', 'FPA', 'FPXE', 'FPXI']
pommesBuden3 = ['FSZ', 'FTA', 'FTAG', 'FTC', 'FTCS', 'FTDS', 'FTGC', 'FTHI', 'FTQI', 'FTRI', 'FTSL', 'FTSM', 'FTXG', 'FTXH', 'FTXL', 'FTXN', 'FTXO', 'FTXR', 'FUND', 'FV', 'FVC', 'FYC', 'FYT', 'FYX', 'GAN', 'GCMG', 'GENY', 'GET', 'GFGF', 'GGLL', 'GGLS', 'GIAC', 'GLDI', 'GMFI', 'GNMA', 'GNOM', 'GO', 'GRID', 'GRNR', 'GTR', 'GXTG', 'HCDI', 'HCDIP', 'HERD', 'HERO', 'HEWG', 'HISF', 'HLAL', 'HNDL', 'HSII', 'HYDR', 'HYLS', 'HYXF', 'HYZD', 'IBB', 'IBBQ', 'IBET', 'IBIT', 'IBTB', 'IBTD', 'IBTE', 'IBTF', 'IBTG', 'IBTH', 'IBTI', 'IBTJ', 'IBTK', 'IBTL', 'IBTM', 'ICLN', 'IDLB', 'IEF', 'IEI', 'IEUS', 'IFGL', 'IFV', 'IGF', 'IGIB', 'IGOV', 'IGSB', 'IHYF', 'III', 'IJT', 'IMCV', 'IMTE', 'INDY', 'IPKW', 'ISDX', 'ISEM', 'ISHG', 'ISHP', 'ISTB', 'IUS', 'IUSB', 'IUSG', 'IUSS', 'IUSV', 'IVCA', 'IVEG', 'IWTR', 'IXUS', 'JANX', 'JEPQ', 'JOET', 'JSMD', 'JSML', 'KACL', 'KBWB', 'KBWD', 'KBWP', 'KBWR', 'KBWY', 'KEJI', 'KRMA', 'KRNT', 'KROP']
pommesBuden4 = ['LATG', 'LDEM', 'LDSF', 'LEGR', 'LMBS', 'LQDA', 'LRGE', 'LRND', 'LVHD', 'MARPS', 'MAXI', 'MBB', 'MCHI', 'MDCP', 'MDGS', 'MDIV', 'MFLX', 'MILN', 'MODL', 'MOR', 'MRND', 'MSFD', 'MSFU', 'MYPS', 'NCNA', 'NEXT', 'NFTY', 'NGM', 'NKEL', 'NKEQ', 'NTZG', 'NUBI', 'NVDS', 'NXTG', 'NZAC', 'NZRO', 'NZUS', 'ODDS', 'ONEQ', 'ORMP', 'PABU', 'PALT', 'PDBA', 'PDBC', 'PDP', 'PEY', 'PEZ', 'PFEL', 'PFES', 'PFF', 'PFI', 'PFM']

